apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joget-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/motrabelsi10/joget-helm.git
    targetRevision: HEAD
    path: joget
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: joget

  syncPolicy:
    automated:   # Active AutoSync
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
